// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 9/17/2024, 10:26:38 AM
const configMerger = require("/home/comborush/Projects/Personal/portfolio-v3/node_modules/.pnpm/@nuxtjs+tailwindcss@6.12.1_magicast@0.3.5_rollup@4.21.3/node_modules/@nuxtjs/tailwindcss/dist/runtime/merger.js");

const inlineConfig = {"content":[],"theme":{"extend":{}},"plugins":[]};

const config = [

].reduce((prev, curr) => configMerger(curr, prev), configMerger(inlineConfig, { content: ["/home/comborush/Projects/Personal/portfolio-v3/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/comborush/Projects/Personal/portfolio-v3/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/comborush/Projects/Personal/portfolio-v3/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/comborush/Projects/Personal/portfolio-v3/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/comborush/Projects/Personal/portfolio-v3/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/comborush/Projects/Personal/portfolio-v3/plugins/**/*.{js,ts,mjs}","/home/comborush/Projects/Personal/portfolio-v3/composables/**/*.{js,ts,mjs}","/home/comborush/Projects/Personal/portfolio-v3/utils/**/*.{js,ts,mjs}","/home/comborush/Projects/Personal/portfolio-v3/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/home/comborush/Projects/Personal/portfolio-v3/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/home/comborush/Projects/Personal/portfolio-v3/app.config.{js,ts,mjs}"] }));

module.exports = (() => {const cfg=config;cfg["content"]["11"] = "/home/comborush/Projects/Personal/portfolio-v3/.nuxt/content-cache/parsed/**/*.{md,yml,yaml,json}";;return cfg;})()
